### ISSUE TITLE
NPM install fails in cointrol/webapp

### ISSUE THREAD

**Issue by bas20150622** [jakubroztocil/cointrol#22]
Got following error when trying to do npm install in cointrol/webapp dir:

> handlebars-brunch@1.10.1 postinstall /Users/xxxxx/Cointrol/cointrol/webapp/node_modules/handlebars-brunch
> node ./postinstall.js

fs.js:144
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:144:11)
    at Object.mkdir (fs.js:745:14)
    at Object.<anonymous> (/Users/bastiaenvanderrest/Cointrol/cointrol/webapp/node_modules/handlebars-brunch/postinstall.js:8:4)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
npm WARN cointrol@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! handlebars-brunch@1.10.1 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the handlebars-brunch@1.10.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by lukacci** [comment]
Same problem here

ADS
==================
> Yapay zekaya dayalı trading sistemi yıllık ortalama %120 kazanç https://paradual.com
