### ISSUE TITLE
on_delete error with django when running "cointrol/manage.py migrate"

### ISSUE THREAD

**Issue by luissantos27** [jakubroztocil/cointrol#24]
Hello, I already tried to solve this without success by following this [article](https://stackoverflow.com/questions/44026548/getting-typeerror-init-missing-1-required-positional-argument-on-delete):

```
(virtualenv) popey@popey-N85-N87-HJ-HJ1-HK1:~/Cointrol$ cointrol/manage.py migrate
Traceback (most recent call last):
  File "cointrol/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/popey/Cointrol/virtualenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/popey/Cointrol/virtualenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/popey/Cointrol/virtualenv/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/popey/Cointrol/virtualenv/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/popey/Cointrol/virtualenv/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/popey/Cointrol/virtualenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/popey/Cointrol/cointrol/cointrol/__init__.py", line 8, in <module>
    django.setup()
  File "/home/popey/Cointrol/virtualenv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/popey/Cointrol/virtualenv/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/popey/Cointrol/virtualenv/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/popey/Cointrol/virtualenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/popey/Cointrol/cointrol/cointrol/core/models.py", line 11, in <module>
    from .castable import CastableModel
  File "/home/popey/Cointrol/cointrol/cointrol/core/castable.py", line 31, in <module>
    class CastableModel(models.Model):
  File "/home/popey/Cointrol/cointrol/cointrol/core/castable.py", line 38, in CastableModel
    null=True,
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by luissantos27** [comment]
I do not know what happened. But I repeated the processed and did not get this error..
