### ISSUE TITLE
cointrol-trader error

### ISSUE THREAD

**Issue by DimaVIII** [jakubroztocil/cointrol#3]
Hello,

if I'm starting cointrol-trader, I'm getting following error, what doses this mean? 

```
[2017-03-11 23:53:50,022 E] cointrol.trader.workers.Ticker: work failed
Traceback (most recent call last):
  File "/root/bitcoin/Cointrol/cointrol/cointrol/trader/workers.py", line 68, in run_forever
    result = yield self.work()
  File "/root/bitcoin/Cointrol/virtualenv/lib/python3.4/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/root/bitcoin/Cointrol/virtualenv/lib/python3.4/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/root/bitcoin/Cointrol/virtualenv/lib/python3.4/site-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/root/bitcoin/Cointrol/cointrol/cointrol/trader/workers.py", line 391, in work
    ticker = yield Task(bitstamp_client.ticker)
  File "/root/bitcoin/Cointrol/virtualenv/lib/python3.4/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/root/bitcoin/Cointrol/virtualenv/lib/python3.4/site-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/root/bitcoin/Cointrol/virtualenv/lib/python3.4/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/root/bitcoin/Cointrol/cointrol/cointrol/trader/bitstamp.py", line 212, in <lambda>
    resp, model_class))
  File "/root/bitcoin/Cointrol/cointrol/cointrol/trader/bitstamp.py", line 250, in _process_response
    data = model_class(data)
  File "/root/bitcoin/Cointrol/cointrol/cointrol/trader/bitstamp.py", line 72, in __init__
    raise ValueError('%s unknown field: %r' % (type(self), key))
ValueError: <class 'cointrol.trader.bitstamp.Ticker'> unknown field: 'open'
will try again
```

**Comment by jakubroztocil** [comment]
Hi @DimaVIII, this means the Bitstamp API has changed. They've added a new field (`open`) to the ticker.

I currently don't have an API key to test it, but it should be easy to fix by yourself:

1. `. virtualenv/bin/activate`

1. Add the `open` field to the [`Ticker` model class](https://github.com/jakubroztocil/cointrol/blob/master/cointrol/core/models.py#L214):

    ```
        open = PriceField()
    ```

1. Make a DB migration file:

    ```shell
    ./manage.py makemigrations
    ```

1. Run the migration on your DB:

    ```shell
    ./manage.py migrate
    ```

1. Try to run the `cointrol-trader` again.

1. If there are more `unknown field` errors, repeat the process.

1. Open a pull request with your changes.

**Comment by LorenzoPanico** [comment]
hi, i have not understood, has cointrol a built-in trading strategy?

**Comment by BubaVV** [comment]
You also need to edit trader/bitstamp.py:

```
class Ticker(Model):
...
'open' : Decimal,
}
```
