### ISSUE TITLE
Unable to brunch build - Windows x64

### ISSUE THREAD

**Issue by AymanEG** [jakubroztocil/cointrol#7]
Hello there ,

Windows x64

step : brunch build

error :

```
You need to have Sass on your system
Execute `gem install sass`
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at Socket._writeGeneric (net.js:711:26)
    at Socket._write (net.js:730:8)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at Socket.Writable.write (_stream_writable.js:243:11)
    at Socket.write (net.js:657:40)
    at Socket.Writable.end (_stream_writable.js:477:10)
    at Socket.end (net.js:427:31)
    at execute (C:\cointrol-bot\cointrol\webapp\node_modules\sass-brunch\lib\index.js:105:25)
    at delay (C:\cointrol-bot\cointrol\webapp\node_modules\sass-brunch\lib\index.js:109:16)
    at SassCompiler.module.exports.SassCompiler.compile (C:\cointrol-bot\cointrol\webapp\node_modules\sass-brunch\lib\index.js:114:12)
    at C:\cointrol-bot\cointrol\webapp\node_modules\brunch\lib\fs_utils\pipeline.js:94:31
    at fn (C:\cointrol-bot\cointrol\webapp\node_modules\async-waterfall\index.js:19:24)
    at Immediate.<anonymous> (C:\cointrol-bot\cointrol\webapp\node_modules\async-waterfall\index.js:58:22)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

I installed ruby and failed to install gem also

```
C:\Ruby24-x64\rubygems-2.6.12>ruby setup.rb --help

C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:72:in `find': unknown encoding name - CP720 (ArgumentError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:72:in `<module:Win32>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/win32/registry.rb:4:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:46:in `require'
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:46:in `iterate_msys_paths'
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:69:in `msys_path'
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:82:in `mingw_bin_path'
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:92:in `enable_dll_search_paths'
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/singleton.rb:27:in `enable_dll_search_paths'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/defaults/operating_system.rb:3:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems.rb:1345:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems.rb:1345:in `<top (required)>'
        from <internal:gem_prelude>:4:in `require'
        from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

Any advice to run simpler interface ?! Also how I can add support for other exchanges like cex.io

**Comment by Arlington1985** [comment]
I have same problem on Ubuntu 17.10. Did you fix your issue?

**Comment by jonathan-daniel** [comment]
`npm install -g sass`
